defaults: &defaults
  app_name: "TesterHome"
  foot_html: "&copy; TesterHome."
  domain: "testerhome.com"
  blog: 'http://blog.testerhome.com'
  video: 'http://video.testerhome.com'
  zhaopin: 'http://testerhome.com/topics/node19'
  admin_emails:
    - "seveniruby@gmail.com"
    - "testwalksun@gmail.com"
    - "lihuazhang@hotmail.com"
    - "snowangelsimon@gmail.com"
    - "humingwei@live.cn"

  google_analytics_key: "UA-45014075-1"
  upload_url: "http://testerhome.com"

  email_server: "smtp.126.com"
  email_sender: 'testerhome@126.com'
  email_password: 'Testerhome2013'
  faye_server: "http://testerhome.com:8080/faye"
  faye_token: "201314"
  faye_client_url: "http://testerhome.com:8080/faye"
 
  # 我们不用upyun了
  # upyun_username: "testerhome"
  # upyun_password: "2012@TesterHome"
  # upyun_bucket: "testerhome"
  # upyun_bucket_domain: "testerhome.b0.upaiyun.com"

  # twitter_token: "uJ9fBa53SmqrHBqs1qq5cg"
  # twitter_secret: "b9e9hbsa9sYYCqmW0kTyfALshclmkQX4kzTm8BBBTw"
  github_token: "56def4f18da4ca15bdca"
  github_secret: "603d7abc7e52bb9c03ea80930a408fa3a5402a26"
  qq_token: "100311590"
  qq_secret: "05cfc257c0e015dfbdb4be7d35927843"
  weibo_token: "491216435"
  weibo_secret: "ed3021318eeea5d749cc31ccd2ffc472"
  # douban_token: "04fab3198986e6350ef0194c9c94b29f"
  # douban_secret: "5c08eac53cfa1890"

  google_js_api_key: "ABQIAAAAC-ble-vmy_g7-Qvem5P86xTX2XchcwgyHzp4Xo0DHRAzt2aLjhQnflwIyCJBOWYCE_rFuUkE0qEmhw"
  google_custom_search_id: "003254291498456785365:gtlmxd6cwlg"
  # 这feed 也已经没有代码了
  # external_feed_url: "http://www.google.com/reader/public/atom/user%2F07401021650408048913%2Flabel%2FTesterHome"
  # external_feed_name: "TesterHome News"

  twitter_id: "testerhome"
  gravatar_proxy: "http://testerhome.com"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
